const x = 10;

try {
    x = 2
  console.log('Continuando o c√≥digo...');
} catch (err) {
  console.log(`Erro: ${err}`);
}
